name = "Lenpack"
author = "oiipo"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "213c6f102bdb29f8ccbbdb22e3f7e0e7ebc15f8283ca5cdb019d38121ed6cf81"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.203"
