name = "Lenpack"
author = "oiipo"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7871dccca4d510f805e74e4271fc14d0135efcac6e4372b3636fc378006a9700"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.203"
