name = "Lenpack"
author = "oiipo"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72ea306b19b845ac40d4cc80eda299afa4b1aa6eaabeba1120d7cfcd5164e708"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.203"
