name = "Lenpack"
author = "oiipo"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f26b04e76b5c6ddd959080028815772de134c2927775390e8a8320f0e832ed15"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.203"
