name = "Lenpack"
author = "oiipo"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ace6a531de21de9a190e40e4c7012c0fc35ca82d8a5b289197d5e261e556198b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.203"
