name = "Lenpack"
author = "oiipo"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2c6b4d209fbf9020adef843b629d96020b73d7efc9a367cee61b3a96b5fdd3a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.203"
